name: deploy-funzocoinkids_landing
run-name: ${{ github.actor }} is deploying funzocoinkids_landing

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            sudo apt-get update -y

            DEPLOY_BASE="/var/www/${{ secrets.DOMAIN }}"
            TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
            RELEASE_DIR="$DEPLOY_BASE/releases/$TIMESTAMP"
            CURRENT_LINK="$DEPLOY_BASE/current"
            sudo mkdir -p "$DEPLOY_BASE/releases"
            sudo chown -R ${{ secrets.USERNAME }}:${{ secrets.USERNAME }} "$DEPLOY_BASE"
            sudo chmod -R 770 "$DEPLOY_BASE"
            sudo find "$DEPLOY_BASE" -type d -exec chmod 2770 {} \;

            # Clone the repository into the release directory
            git clone https://${{ secrets.USER_KEY }}@github.com/nickfff-dev/funzocoinkids_landing.git "$RELEASE_DIR"
            cd "$RELEASE_DIR"

            cat <<EOF > .env.local
            NEXT_PUBLIC_LANDING_URL=${{ secrets.NEXT_PUBLIC_LANDING_URL }}
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
            NODE_ENV=production
            EOF

            # Setup Node environment
            export NVM_DIR="/home/${{ secrets.USERNAME }}/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use --lts

            # Ensure pm2 is installed
            if ! command -v pm2 &> /dev/null; then
              npm install -g pm2
            fi

            # Permissions
            sudo chown -R ${{ secrets.USERNAME }}:${{ secrets.USERNAME }} "$RELEASE_DIR"
            sudo chmod -R u+rwX "$RELEASE_DIR"
            sudo chmod -R g+rwX "$RELEASE_DIR"
            sudo find "$RELEASE_DIR" -type d -exec chmod 2770 {} \;

            pnpm install
            pnpm build
            if [ $? -ne 0 ]; then
              echo "Build failed"
              exit 1
            fi

            # Set permissions for the release directory
            sudo chown -R ${{ secrets.USERNAME }}:${{ secrets.USERNAME }} "$RELEASE_DIR"
            sudo chmod -R 770 "$RELEASE_DIR"
            sudo chmod -R g+rwX "$RELEASE_DIR"
            sudo find "$RELEASE_DIR" -type d -exec chmod 2770 {} \;
            ln -sfn "$RELEASE_DIR" "$CURRENT_LINK"

            # PM2 reload/start
            if pm2 ls | grep -qw '\s${{ secrets.DOMAIN }}'; then
              pm2 reload ${{ secrets.DOMAIN }} --time --update-env --cwd "$CURRENT_LINK"
            else
              pm2 start pnpm --time --cwd "$CURRENT_LINK" --name "${{ secrets.DOMAIN }}" -- start
            fi
            pm2 save

            # Clean up old releases, keeping last 3
            cd "$DEPLOY_BASE/releases"
            ls -1tr | head -n -3 | xargs -d '\n' rm -rf --
